function params = mototrak_diff_reward_default_params(varargin)

    default_params = struct(...
        'animal_name'       , 'jan-01-01',...
        'trial_type'        , {{'jackpot', 'single', 'no_reward'}},...
        'trial_type_pct'    , [25 50 25],...
        'num_pellets'       , [5 1 0],...
        'trial_type_sounds' , [13000 7000 10000],...
        'reward_sound'      , 4000 ,...
        'trial_type_digout' , [2 1 7],... %number of digital pulses for each trial type
        'hit_window'        , 5,...
        'cno'               , false,...
        'duration'          , 40*60,...
        'bypass_training'   , false,...
        'mastication_time'  , 5,...
        'pellets_pause'     , 1.5,...
        'force_target'      , 80,...
        'hold_time'         , 0.8,...
        'init_thresh'       , 10,...
        'lever_pos'         , 350, ...
        'task_level'        , 4,...
        'save_dir'          , 'D:\customized_behavioral_task_results\' ...
        );
    
    if nargin
        params = varargin{1};
        %some parameters are provided as argument, fill the rest:
        all_param_names = fieldnames(default_params);
        for i=1:numel(all_param_names)
            if ~isfield(params,all_param_names(i))
                params.(all_param_names{i}) = default_params.(all_param_names{i});
            end
        end
    else
        params = default_params;
    end
    