function params = mototrak_diff_reward_default_params(varargin)

    default_params = struct(...
        ... %modifiable params
        'animal_name'        , 'jan-01-01',...
        'trial_type'         , {{'jackpot', 'single', 'no_reward'}},...
        'trial_type_pct'     , [25 50 25],...
        'num_pellets'        , [5 1 0],...
        'trial_type_sounds'  , [7000 10000 13000],...
        'trial_type_digout'  , [2 1 7],... %number of digital pulses for each trial type
        'intervale_type'     , {{'intervale_1'}},...
        'min_intervale'      , [15 ],...
        'max_intervale'      , [200],...
        'intervale_type_pct' , [100],...
        'hit_window'         , 5,...
        'cno'                , false,...
        'duration'           , 30*60,...
        'force_target'       , 80,...
        'hold_time'          , 0.8,...
        'adapt_hold_time'    , false,...
        'hold_time_max'      , 0.8,...        
        'adapt_force'        , false,...
        'force_max'          , 80,...
        'adapt_distance'     , false,...
        'distance_max'       , 0.75,...
        'lever_pos'          , 0.75,...  
        'min_int'            , 1,...
        'sound'              , true,...
        'synchronisation'    , false,...
        ... % fixed params
        'session_number'     , 0,...
        'past_10_trials_succ', false(1,10),...
        'reward_sound'       , 4000 ,...
        'mastication_time'   , 7,...
        'pellets_pause'      , 1.5,...
        'init_thresh'        , 10,...
        'task_level'         , 4,...
        'save_dir'           , 'D:\customized_behavioral_task_results\jan-01-01\', ...
        'fbuf_dur'           , 0.5 ...
        );
    
    if nargin
        params = varargin{1};
        %some parameters are provided as argument, fill the rest:
        all_param_names = fieldnames(default_params);
        for i=1:numel(all_param_names)
            if ~isfield(params,all_param_names(i))
                params.(all_param_names{i}) = default_params.(all_param_names{i});
            end
        end
    else
        params = default_params;
    end
    